name: "Run Checks"
on:
  workflow_dispatch: {}
  pull_request:
    branches:
    - main

jobs:
  fmt:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          extra-platforms = aarch64-linux
    - run: |
        nix fmt .
        git diff-files --quiet || (git -P diff; echo -e "\nNOT FORMATTED: run 'nix fmt .'"; false)
